### ISSUE TITLE
Multiline command

### ISSUE THREAD

**Issue by Silvus** [fabioxgn/go-bot#25]
Hi,

It is possible for a command to return multiple lines?
Apparently, include a CR-LF character ("\ r \ n") in the string does not work.

**Comment by Silvus** [comment]
To gain flexibility, you should probably pass the `ircConnection` to the command, and maybe  add some go-ircevent functions to it (like `SendRaw()`).
As for the `part(c *Cmd, channel, senderNick string, conn ircConnection)` command, for example.

This way, a command would have the following signature :

```go

func count(command *bot.Cmd, channel, senderNick string, conn ircConnection) (err error) {
    for i := 0; i <= 2; i++ {
        conn.Privmsg(channel, "my message")
    }
    return nil
}
```

I'm not a Go expert, it can work?

**Comment by fabioxgn** [comment]
@Silvus I'll check into the multiline return. I guess it makes sense to send multiple messages, splitting on `\n`. I'll implement that.

As about passing the IRC Connection, I'd like to avoid that, as I plan to implement other protocols like Slack, and passing the connection goes agains the idea behind the bot package, which is to abstract the connection stuff and provide a simple way to write new and "safe" to use plugins.

**Comment by Silvus** [comment]
Ok, I understand, but you could not make a counter every second, for example.
Never mind, I'll look directly into go-ircevent.

Thanks
